name: Unit and Integration Tests Runner

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lints
        run: yarn lint

      # Auto-downloads the platform specific language server (see https://github.com/ink-analyzer/ink-vscode/blob/master/setup.js).
      - name: Run tests (Windows and macOS)
        if: inputs.os != 'ubuntu-latest'
        env:
          # Used by the setup script,
          # otherwise we sometimes get hit by rate limits when determining the latest release from the GitHub API.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn test

      - name: Run tests (Linux)
        if: inputs.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xvfb-run -a yarn test
