name: Unit and Integration Tests Runner

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lints
        run: yarn lint

      - name: Run tests (Windows and macOS)
        if: inputs.os != 'ubuntu-latest'
        run: yarn test

      - name: Run tests (Linux)
        if: inputs.os == 'ubuntu-latest'
        run: xvfb-run -a yarn test
